# Generated by Django 3.2.15 on 2022-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pateint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('detail', models.TextField()),
                ('precount', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('next_visit_date', models.DateTimeField()),
            ],
        ),
    ]
